export const authCopy = {
  register: {
    title: "Create your organisation",
    description: "Start with a verified Owner-Operator account. You will confirm your email before signing in.",
    submit: "Create account",
    submitting: "Creating account...",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
  },
  login: {
    title: "Sign in",
    description: "Use your Buffr Checkpoint work email.",
    submit: "Sign in",
    submitting: "Signing in...",
    noAccount: "No account yet?",
    createOne: "Create one",
  },
  checkEmail: {
    title: "Check your email",
    description:
      "We sent a confirmation link to your inbox. Open it to verify your address and continue setup. The link expires in 24 hours.",
    resend: "Resend confirmation email",
    resending: "Sending...",
    resent: "If an unverified account exists for that email, a new link is on the way.",
    backToSignIn: "Back to sign in",
  },
  verifyEmail: {
    title: "Verifying your email",
    successTitle: "Email verified",
    successDescription: "Your account is confirmed. Continue to authenticator setup.",
    expiredTitle: "Link expired or invalid",
    expiredDescription: "Request a new confirmation email and try again.",
    continue: "Continue to MFA setup",
    requestNew: "Request a new link",
  },
  mfaSetup: {
    title: "Set up authenticator MFA",
    description:
      "Scan the QR code with your authenticator app, or enter the secret manually, then confirm with a 6-digit code.",
    scanHint: "Open Google Authenticator, 1Password, Authy, or similar and scan this code.",
    showManual: "Can't scan? Enter the secret manually",
    hideManual: "Hide manual setup details",
    secretLabel: "Secret",
    otpauthLabel: "otpauth URL",
    codeLabel: "Authenticator code",
    preparing: "Preparing authenticator QR code...",
    confirm: "Confirm and save recovery codes",
    confirming: "Confirming...",
    recoveryTitle: "Save your recovery codes",
    recoveryDescription:
      "Store these one-time codes somewhere safe. Each code can unlock your account once if you lose your authenticator.",
    continueOnboarding: "Continue onboarding",
  },
  mfaChallenge: {
    title: "Authenticator check",
    description: "Enter the 6-digit code from your authenticator app, or use a recovery code.",
    ttlHint: "This check expires 10 minutes after you sign in. If it expires, sign in again.",
    submit: "Verify",
    submitting: "Verifying...",
    useRecovery: "Use a recovery code instead",
    useTotp: "Use authenticator code instead",
    missingToken: "No active sign-in challenge in this browser tab.",
    backToSignIn: "Back to sign in",
  },
  forgotPassword: {
    title: "Reset your password",
    description: "Enter your work email. If an account exists, we send a reset link.",
    submit: "Send reset link",
    submitting: "Sending...",
    sent: "If an account exists for that email, a reset link is on the way.",
    backToSignIn: "Back to sign in",
  },
  resetPassword: {
    title: "Choose a new password",
    description: "Use at least 8 characters. You will sign in again after saving.",
    submit: "Update password",
    submitting: "Updating...",
    missingToken: "This reset link is missing or incomplete. Request a new one.",
  },
  errors: {
    emailVerificationRequired: "Confirm your email before signing in. Check your inbox for the link.",
    mfaRequired: "Enter your authenticator code to finish signing in.",
    lockedOut:
      "Too many failed sign-in attempts. Wait a few minutes or use Forgot password, then try again.",
    generic: "Something went wrong. Try again.",
  },
} as const;
