export const authCopy = {
  register: {
    title: "Create your organisation",
    description: "Start with a verified Owner-Operator account. You will confirm your email before signing in.",
    submit: "Create account",
    submitting: "Creating account...",
    haveAccount: "Already have an account?",
    signIn: "Sign in",
    terms: {
      agree: "I agree to the",
      and: "and the",
      termsLink: "Terms and Conditions",
      privacyLink: "Privacy Policy",
      required: "Please accept the Terms and Conditions and the Privacy Policy to create your account.",
    },
  },
  buffrId: {
    continue: "Continue with Buffr ID",
    or: "Or use your Checkpoint password",
    registerContinue: "Continue with Buffr ID",
    registerNote: "You will create or sign in to your Buffr ID, then your organisation is set up here.",
    securityTitle: "Two-step sign-in is managed in Buffr ID",
    securityDescription: "Turn on two-step sign-in in your Buffr ID account, then come back and sign in again.",
    securityLink: "Open Buffr ID security",
    errors: {
      buffr_id_unavailable: "Buffr ID sign-in is not available right now. Try again shortly.",
      buffr_id_state: "That sign-in expired or did not start here. Start again.",
      buffr_id_denied: "Buffr ID sign-in was cancelled.",
      buffr_id_token: "Buffr ID could not confirm your sign-in. Try again.",
      buffr_id_forbidden: "This account must turn on two-step sign-in in Buffr ID, then sign in again.",
      buffr_id_failed: "We could not sign you in with Buffr ID. Try again or contact support.",
      no_account: "There is no Checkpoint organisation for this Buffr ID yet. Create your organisation below.",
      details_required: "Enter your organisation name and sector first.",
      terms_required: "Please accept the Terms and Conditions and the Privacy Policy to create your account.",
      busy: "Sign-up is busy right now. Try again later.",
      create_failed: "We could not create your organisation. Try again or contact support.",
    } as Record<string, string>,
  },
  login: {
    title: "Sign in",
    description: "Use your work email.",
    submit: "Sign in",
    submitting: "Signing in...",
    noAccount: "No account yet?",
    createOne: "Create one",
  },
  checkEmail: {
    title: "Check your email",
    description:
      "We sent a confirmation link to your inbox. Open it to verify your address and continue setup. The link expires in 24 hours.",
    resend: "Resend confirmation email",
    resending: "Sending...",
    resent: "If an unverified account exists for that email, a new link is on the way.",
    backToSignIn: "Back to sign in",
  },
  verifyEmail: {
    title: "Verifying your email",
    successTitle: "Email verified",
    confirmDescription: "Confirm that this is your email address to finish creating your account.",
    confirm: "Confirm my email",
    successDescription: "Your account is confirmed. Continue to set up your organisation.",
    expiredTitle: "Link expired or invalid",
    expiredDescription: "Request a new confirmation email and try again.",
    continue: "Continue",
    requestNew: "Request a new link",
  },
  mfaSetup: {
    title: "Set up authenticator MFA",
    description:
      "Scan the QR code with your authenticator app, or enter the secret manually, then confirm with a 6-digit code.",
    scanHint: "Open Google Authenticator, 1Password, Authy, or similar and scan this code.",
    showManual: "Can't scan? Enter the secret manually",
    hideManual: "Hide manual setup details",
    secretLabel: "Secret",
    otpauthLabel: "otpauth URL",
    codeLabel: "Authenticator code",
    preparing: "Preparing authenticator QR code...",
    confirm: "Confirm and save recovery codes",
    confirming: "Confirming...",
    recoveryTitle: "Save your recovery codes",
    recoveryDescription:
      "Store these one-time codes somewhere safe. Each code can unlock your account once if you lose your authenticator.",
    continueOnboarding: "Continue onboarding",
  },
  mfaChallenge: {
    title: "Authenticator check",
    description: "Enter the 6-digit code from your authenticator app, or use a recovery code.",
    ttlHint: "This check expires 10 minutes after you sign in. If it expires, sign in again.",
    submit: "Verify",
    submitting: "Verifying...",
    useRecovery: "Use a recovery code instead",
    useTotp: "Use authenticator code instead",
    missingToken: "Authenticator challenge continues via a secure cookie if this tab lost its sessionStorage copy.",
    backToSignIn: "Back to sign in",
  },
  forgotPassword: {
    title: "Reset your password",
    description: "Enter your work email. If an account exists, we send a reset link.",
    submit: "Send reset link",
    submitting: "Sending...",
    sent: "If an account exists for that email, a reset link is on the way.",
    backToSignIn: "Back to sign in",
  },
  resetPassword: {
    title: "Choose a new password",
    description: "Use at least 8 characters. You will sign in again after saving.",
    submit: "Update password",
    submitting: "Updating...",
    missingToken: "This reset link is missing or incomplete. Request a new one.",
  },
  errors: {
    emailVerificationRequired: "Confirm your email before signing in. Check your inbox for the link.",
    mfaRequired: "Enter your authenticator code to finish signing in.",
    lockedOut: "Too many failed sign-in attempts. Wait a few minutes or use Forgot password, then try again.",
    generic: "Something went wrong. Try again.",
  },
} as const;
